### PR TITLE
T1518

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @ScottDowne received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/2eecc9f6e287cfb/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/2eecc9f6e287cfb/output.txt

Total script time: 0.64 mins

Server is running on http://pr499.butyr.org/templates/test.html

**Comment by brettgaylor** [comment]
Scott - I'm seeing the default event, that says "this is a test", within the wrong target area

Other than that, PR+

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @ScottDowne received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/074f24ad8aaf578/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/074f24ad8aaf578/output.txt

Total script time: 0.22 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @ScottDowne received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/17b5a3972a40732/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/17b5a3972a40732/output.txt

Total script time: 0.89 mins

Server is running on http://pr499.butyr.org/templates/test.html

**Pull request merged**
