### PR TITLE
M t1333

### PR DESCRIPTION
**Pull request by k88hudson**
Templates: testing Zoink plugin

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/05b22be3e9a2124/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/05b22be3e9a2124/output.txt

Total script time: 0.47 mins

Server is running on http://pr376.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Obsoleted by pull request #433

**Pull request closed without merging**
