### PR TITLE
[#2033] Fixed config issue for repeat plugin

### PR DESCRIPTION
**Pull request by dseif**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @humphd received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/81d6e4c7ce1d729/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @humphd received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/906e3d96113de6d/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/81d6e4c7ce1d729/output.txt

Total script time: 0.99 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/906e3d96113de6d/output.txt

Total script time: 0.69 mins

Server is running on http://pr812.butyr.org/templates/basic/
Run the Test Suite: http://pr812.butyr.org/test/

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/8c5a1f6240fc4980ab5fc9ed9b2cd50ffc1dc421

**Pull request closed without merging**
