### PR TITLE
M t1337

### PR DESCRIPTION
**Pull request by k88hudson**
Templates: testing html framework for newscaster

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/d346763984e6930/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/d346763984e6930/output.txt

Total script time: 0.57 mins

Server is running on http://pr377.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Resolved by another ticket

**Pull request closed without merging**
