### PR TITLE
[#1248] Move as much CSS as possible to LESS

### PR DESCRIPTION
**Pull request by mjschranz**
https://webmademovies.lighthouseapp.com/projects/65733/tickets/1248-move-as-much-css-as-possible-to-stylus

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @secretrobotron received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/5a5f7666bde1a9c/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/5a5f7666bde1a9c/output.txt

Total script time: 0.70 mins

Server is running on http://pr653.butyr.org/templates/test.html

**Comment by mjschranz** [comment]
Closing in favor of #654

**Pull request closed without merging**
