### PR TITLE
Fixin teh swarm

### PR DESCRIPTION
**Pull request by mjschranz**
testing fixing the tests running on swarm.

Also removing cornfield from tests list. They aren't completely automated so they should not be in this list.

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_try** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/19138ed48877fb5/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/19138ed48877fb5/output.txt

Total script time: 2.00 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_try** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/0cb13a46c30a69a/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_try** from @mjschranz received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/936ad9e9cb234b9/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/0cb13a46c30a69a/output.txt

Total script time: 1.53 mins

Your job has been submitted to the swarm! see http://norway.proximity.on.ca/user/butter

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/936ad9e9cb234b9/output.txt

Total script time: 0.80 mins

Your job has been submitted to the swarm! see http://norway.proximity.on.ca/user/butter

**Comment by mjschranz** [comment]
Was used for testing

**Pull request closed without merging**
