### PR TITLE
[#1773] only load unload dialog if ui exists.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/f2d40185ca9e0c8/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/f2d40185ca9e0c8/output.txt

Total script time: 0.38 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/8da7f2fa1ec45d1/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/8da7f2fa1ec45d1/output.txt

Total script time: 0.59 mins

Server is running on http://pr642.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/d9267318ffa70099cfa6c3256f3c337e5974c08a

**Pull request closed without merging**
