### PR TITLE
[#1209] Plugin scripts no longer load again if it alraedy exists

### PR DESCRIPTION
**Pull request by dseif**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @humphd received. Current queue size: 0

Live output at: http://butyr.org:8000/6d24eb7261764af/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/6d24eb7261764af/output.txt

Total script time: 0.40 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @humphd received. Current queue size: 0

Live output at: http://butyr.org:8000/8a3b5b049e130a0/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/8a3b5b049e130a0/output.txt

Total script time: 0.69 mins

Server is running on http://pr307.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @ScottDowne received. Current queue size: 0

Live output at: http://botio.butyr.org:80/9555b18f55e284a/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:80/9555b18f55e284a/output.txt

Total script time: 0.33 mins

**Comment by dseif** [comment]
Closing in favor of https://github.com/mozilla/butter/pull/322 as it is rebased off master

**Pull request closed without merging**
