### PR TITLE
[#1938] Fixed issue where editor unit tests were using query selector on...

### PR DESCRIPTION
**Pull request by dseif**
... wrong element/class

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/66a7b8e8d630624/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/66a7b8e8d630624/output.txt

Total script time: 1.35 mins

Server is running on http://pr741.butyr.org/templates/basic/

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/a816030802ec635468b31223327fc2fb501dd2f8

**Pull request closed without merging**
