### PR TITLE
TESTING PROTOTYPE

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/e33b45ca7143996/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/e33b45ca7143996/output.txt

Total script time: 0.77 mins

Server is running on http://pr783.butyr.org/templates/basic/
Run the Test Suite: http://pr783.butyr.org/test/

**Comment by jbuck** [comment]
It's not clear to me what ticket this belongs to... so closing

**Pull request closed without merging**
