### PR TITLE
M t1329

### PR DESCRIPTION
**Pull request by k88hudson**
Templates - testing context switcher plugin

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/1a49767ad711673/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/1a49767ad711673/output.txt

Total script time: 0.42 mins

Server is running on http://pr375.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/31d6b123944ba56/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/31d6b123944ba56/output.txt

Total script time: 0.47 mins

Server is running on http://pr375.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/0424fe6cd6d9088/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/0424fe6cd6d9088/output.txt

Total script time: 1.13 mins

Server is running on http://pr375.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Obsoleted by pull request #425

**Pull request closed without merging**
