### PR TITLE
[#2063] Silly hack for IE9 support in Editor Layout Loading. I'm terribl...

### PR DESCRIPTION
**Pull request by cadecairos**
...y sorry for this code :(

### CODE REVIEW

**Comment by cadecairos** [comment]
bug in question: https://webmademovies.lighthouseapp.com/projects/65733-popcorn-maker/tickets/2063-ie9-fix-editor-layout-loading

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/0f1c2d8e0646ff4/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/0f1c2d8e0646ff4/output.txt

Total script time: 0.76 mins

Server is running on http://pr831.butyr.org/templates/basic/
Run the Test Suite: http://pr831.butyr.org/test/

**Pull request closed without merging**
