### PR TITLE
T1453

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/d29ee0b616b497c/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/db51b62110969a5/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/d29ee0b616b497c/output.txt

Total script time: 0.30 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/db51b62110969a5/output.txt

Total script time: 0.74 mins

Server is running on http://pr538.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Closing in favour of pull request #560

**Pull request closed without merging**
