### PR TITLE
[#2154] Double clicking track events in plugin list editor now create new track event

### PR DESCRIPTION
**Pull request by mjschranz**
https://webmademovies.lighthouseapp.com/projects/65733/tickets/2154-clicking-track-event-in-tray-should-create-an-event

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @brett-etherworks received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/c2be5e0245ae0bf/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/c2be5e0245ae0bf/output.txt

Total script time: 1.32 mins

Server is running on http://pr943.butyr.org/templates/basic/
Run the Test Suite: http://pr943.butyr.org/test/

**Comment by mjschranz** [comment]
Another ticket is covering this instead.

**Pull request closed without merging**
