### PR TITLE
[#t1902] Making proper call to trackevent update inside frame left and r...

### PR DESCRIPTION
**Pull request by ScottDowne**
...ight, so view and popcornwrapper updates also get called from one spot.

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @secretrobotron received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/8483c1775ef510e/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @secretrobotron received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/797a8ea6eb5c143/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/8483c1775ef510e/output.txt

Total script time: 0.72 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/797a8ea6eb5c143/output.txt

Total script time: 0.92 mins

Server is running on http://pr718.butyr.org/templates/basic/

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_cleanup** from @secretrobotron received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/7edcba9006eb963/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/7edcba9006eb963/output.txt

Total script time: 0.27 mins

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/73c65e376b5960d41a48e11d94144163b11146a4

**Pull request closed without merging**
