### PR TITLE
1534 Add IE supported .woff fonts

### PR DESCRIPTION
**Pull request by stanica**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @cadecairos received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/d1d1b6048534e02/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @cadecairos received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/495094272d2230f/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/d1d1b6048534e02/output.txt

Total script time: 0.40 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/495094272d2230f/output.txt

Total script time: 0.70 mins

Server is running on http://pr531.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @cadecairos received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/59ed1663cfafe2c/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_cleanup** from @cadecairos received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/bc569c38497d6db/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/59ed1663cfafe2c/output.txt

Total script time: 1.09 mins

Server is running on http://pr531.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/bc569c38497d6db/output.txt

Total script time: 0.37 mins

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/7150a57859c67edd97f213a461910c91db8303ff

**Pull request closed without merging**
