### PR TITLE
[#1801] Popcorn Maker Text Plugin. Structure in place for future information to be passed from editors

### PR DESCRIPTION
**Pull request by mjschranz**
https://webmademovies.lighthouseapp.com/projects/65733/tickets/1801-write-a-text-plugin

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @ScottDowne received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/8fd77d1489a39d8/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/8fd77d1489a39d8/output.txt

Total script time: 0.70 mins

Server is running on http://pr719.butyr.org/templates/basic/

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @ScottDowne received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/50e4898304415d0/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/50e4898304415d0/output.txt

Total script time: 0.59 mins

**Comment by mjschranz** [comment]
Finished by #799

**Pull request closed without merging**
