### PR TITLE
T1782

### PR DESCRIPTION
**Pull request by humphd**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/2cc0a86be8707d8/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/2cc0a86be8707d8/output.txt

Total script time: 0.69 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/72a7bc5edfdf465/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/72a7bc5edfdf465/output.txt

Total script time: 0.87 mins

Server is running on http://pr724.butyr.org/templates/basic/

**Comment by jbuck** [comment]
Closing in favour of #728

**Pull request closed without merging**
