### PR TITLE
[t1707] fixed css and corresponding js

### PR DESCRIPTION
**Pull request by secretrobotron**
1. Removed data-ui-state attribute from tray
2. Used .minimized instead
3. Fixed src/ui/ui.js to use the change

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/91ba054d912a0fb/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/91ba054d912a0fb/output.txt

Total script time: 0.80 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/91ff4d86a77bb30/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/91ff4d86a77bb30/output.txt

Total script time: 0.55 mins

Server is running on http://pr615.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/c5fabbe8404ca8d7b987f31658

**Pull request closed without merging**
