### PR TITLE
T1609

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @humphd received. Current queue size: 2

Live output at: http://botio.butyr.org:8000/0a5d3f44cae129b/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/0a5d3f44cae129b/output.txt

Total script time: 0.89 mins

Server is running on http://pr559.butyr.org/templates/test.html

**Comment by dseif** [comment]
haha
/botio check

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @dseif received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/dd6a9f44d779e74/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/dd6a9f44d779e74/output.txt

Total script time: 0.56 mins

**Pull request merged**
