### PR TITLE
[#1937] Initial controls volume state is wrong.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @humphd received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/63bc931fc8e91db/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @humphd received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/bc660a7b37a7a25/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/63bc931fc8e91db/output.txt

Total script time: 0.68 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/bc660a7b37a7a25/output.txt

Total script time: 1.33 mins

Server is running on http://pr742.butyr.org/templates/basic/

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @humphd received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/bd162b496da36a3/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @humphd received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/0872c591c3956be/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/bd162b496da36a3/output.txt

Total script time: 0.69 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/0872c591c3956be/output.txt

Total script time: 0.72 mins

Server is running on http://pr742.butyr.org/templates/basic/

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/deb14ea71e65e079d704b02792bffce14406b122

**Pull request closed without merging**
