### PR TITLE
[#1786] Trackevents no longer overlap but inhabit the track below instea...

### PR DESCRIPTION
**Pull request by dseif**
...d or create a new one

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @dseif received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/8ba15e7d05896ad/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/8ba15e7d05896ad/output.txt

Total script time: 0.99 mins

Server is running on http://pr748.butyr.org/templates/basic/

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/987ff9b32e7b597acd671792d4641881791827b3

**Pull request closed without merging**
