### PR TITLE
[#1978] update popcorn.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @ScottDowne received. Current queue size: 2

Live output at: http://botio.butyr.org:8000/ec543daf9cd4c52/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/ec543daf9cd4c52/output.txt

Total script time: 0.79 mins

Server is running on http://pr772.butyr.org/templates/basic/
Run the Test Suite: http://pr772.butyr.org/test/

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/3216d6d674bedfc3c463663919255e4f4678c1b3

**Pull request closed without merging**
