### PR TITLE
[EMBED] Preview page

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/02416f7a337f096/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/02416f7a337f096/output.txt

Total script time: 0.65 mins

Server is running on http://pr791.butyr.org/templates/basic/
Run the Test Suite: http://pr791.butyr.org/test/

**Comment by jbuck** [comment]
Humph did this is another ticket I believe

**Pull request closed without merging**
