### PR TITLE
M t1335

### PR DESCRIPTION
**Pull request by k88hudson**
Testing for tempaltes - editor supporting 'hidden' and target in manifest

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/b2d85d59efea10a/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/b2d85d59efea10a/output.txt

Total script time: 0.93 mins

Server is running on http://pr374.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Lighthouse ticket was marked resolved

**Pull request closed without merging**
