### PR TITLE
T1421b

### PR DESCRIPTION
**Pull request by dseif**
...ur tests to look for the proper string in the generated popcorn code

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @humphd received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/6e2ead0cb03d061/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @humphd received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/40d7751c4d4bc9a/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/6e2ead0cb03d061/output.txt

Total script time: 0.43 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/40d7751c4d4bc9a/output.txt

Total script time: 0.49 mins

Server is running on http://pr437.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Resolved by pull request #438

**Pull request closed without merging**
