### PR TITLE
[#1330] added hold css class to media change url.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @secretrobotron received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/abe874c8a27f4b0/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/abe874c8a27f4b0/output.txt

Total script time: 0.55 mins

Server is running on http://pr365.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Staged on storycamp: https://github.com/mozilla/butter/compare/753aa0f418ad...204d4aa7bc5a

**Pull request closed without merging**
