### PR TITLE
[1917] Add simple close handler for share panel close button

### PR DESCRIPTION
**Pull request by humphd**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/090a0832397c3d0/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/090a0832397c3d0/output.txt

Total script time: 0.87 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/281a992dde35a92/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/281a992dde35a92/output.txt

Total script time: 1.45 mins

Server is running on http://pr723.butyr.org/templates/basic/

**Comment by jbuck** [comment]
Rebased on master: https://github.com/mozilla/butter/commit/d114e6bc3dedb59d63c446947dc2ba2cec8b27d9

**Pull request closed without merging**
