### PR TITLE
M 725

### PR DESCRIPTION
**Pull request by k88hudson**
Templates - testing

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/7e0494f4f015a3e/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/7e0494f4f015a3e/output.txt

Total script time: 0.42 mins

Server is running on http://pr371.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Resolved by pull request #419

**Pull request closed without merging**
