### PR TITLE
[#1287] Fixed issue where target drop downs were only being created if t...

### PR DESCRIPTION
**Pull request by dseif**
...hey were in the manifest

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @cadecairos received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/65294fbd0c1c5c3/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @cadecairos received. Current queue size: 2

Live output at: http://botio.butyr.org:8000/fbbcf97d35478ee/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/65294fbd0c1c5c3/output.txt

Total script time: 0.63 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/fbbcf97d35478ee/output.txt

Total script time: 0.93 mins

Server is running on http://pr347.butyr.org/templates/test.html

**Comment by dseif** [comment]
Messed this up again somehow, use this one please https://github.com/mozilla/butter/pull/357/files

**Pull request closed without merging**
