### PR TITLE
M t1340

### PR DESCRIPTION
**Pull request by k88hudson**
Testing for templates

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/1e601eedd3196b7/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/1e601eedd3196b7/output.txt

Total script time: 0.78 mins

Server is running on http://pr367.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/199fd2bc62884fd/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/199fd2bc62884fd/output.txt

Total script time: 1.33 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/93d4a2d335144cb/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/93d4a2d335144cb/output.txt

Total script time: 1.32 mins

**Comment by jbuck** [comment]
Resolved by pull request #419

**Pull request closed without merging**
