### PR TITLE
[#2218] Update popcorn submodule for SoundCloud fixes etc.

### PR DESCRIPTION
**Pull request by humphd**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @humphd received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/d1a61dcf3ea3d5c/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/d1a61dcf3ea3d5c/output.txt

Total script time: 0.79 mins

Server is running on http://pr921.butyr.org/templates/basic/
Run the Test Suite: http://pr921.butyr.org/test/

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/368f98b84abb6c70bef64205e174514380bc72ab

**Pull request closed without merging**
