### PR TITLE
[#2053] Butter Highlight div was preventing any dragging for our plugins

### PR DESCRIPTION
**Pull request by mjschranz**
https://webmademovies.lighthouseapp.com/projects/65733/tickets/2053-plugin-editors-no-longer-support-draggingresizing

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @secretrobotron received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/e6650a5083f6315/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/e6650a5083f6315/output.txt

Total script time: 0.57 mins

Server is running on http://pr835.butyr.org/templates/basic/
Run the Test Suite: http://pr835.butyr.org/test/

**Comment by mjschranz** [comment]
Ticket was resolved by #2057 in Lighthouse.

**Pull request closed without merging**
