### PR TITLE
Bug 1759 - Make dialogs a static define so rjs can read it. r=bobby

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @secretrobotron received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/98c5d943fdbb597/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/98c5d943fdbb597/output.txt

Total script time: 0.32 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/95850da2a12eb88/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/95850da2a12eb88/output.txt

Total script time: 0.25 mins

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/f0548562a6c1102a470c141aa2459a52e45bf2da

**Pull request closed without merging**
