### PR TITLE
Testing new robots template style

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/b8411b7a4cc7360/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/b8411b7a4cc7360/output.txt

Total script time: 0.61 mins

Server is running on http://pr544.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/5f3afdb89e0a409/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/5f3afdb89e0a409/output.txt

Total script time: 0.58 mins

Server is running on http://pr544.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Old ticket

**Pull request closed without merging**
