### PR TITLE
T1658

### PR DESCRIPTION
**Pull request by cadecairos**
...s. [#1658]

### CODE REVIEW

**Comment by cadecairos** [comment]
https://webmademovies.lighthouseapp.com/projects/65733-popcorn-maker/tickets/1658-twitter-plugin-is-throwing-error-on-simple-template-load#ticket-1658-6

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @humphd received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/0932ac6c7056a1a/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/0932ac6c7056a1a/output.txt

Total script time: 0.80 mins

Server is running on http://pr595.butyr.org/templates/test.html

**Pull request merged**
