### PR TITLE
Musictime

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/e0718979ab793a6/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/e0718979ab793a6/output.txt

Total script time: 2.00 mins

**Comment by jbuck** [comment]
the band plays no more

**Pull request closed without merging**
