### PR TITLE
[#1966] added back publish.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/3d79e6874485bd2/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/9a758af35f4a2c4/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/3d79e6874485bd2/output.txt

Total script time: 1.30 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/9a758af35f4a2c4/output.txt

Total script time: 0.87 mins

Server is running on http://pr762.butyr.org/templates/basic/
Run the Test Suite: http://pr762.butyr.org/test/

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/dc6a341283a9d57/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/dc6a341283a9d57/output.txt

Total script time: 1.00 mins

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/1c021ad12583ba33045e71fa1f4d514aa9345330

**Pull request closed without merging**
