### PR TITLE
Report css linting in check-css

### PR DESCRIPTION
**Pull request by humphd**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/1580077a32654bf/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/1580077a32654bf/output.txt

Total script time: 0.44 mins

**Comment by jbuck** [comment]
Time to update the botio check script...

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/ddb02e09ad6e75d/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/ddb02e09ad6e75d/output.txt

Total script time: 0.23 mins

**Comment by jbuck** [comment]
Hooray! PR+

**Pull request merged**
