### PR TITLE
T363

### PR DESCRIPTION
**Pull request by secretrobotron**
WIP!!

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @secretrobotron received. Current queue size: 0

Live output at: http://butyr.org:8000/03a697c5b0c699c/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/03a697c5b0c699c/output.txt

Total script time: 0.69 mins

Server is running on http://pr305.butyr.org/templates/test.html

**Comment by benrito** [comment]
Cool! Neat to see it starting to come together.

**Pull request closed without merging**
