### PR TITLE
[#1237] HTML5 media attributes no longer get copied to media divs

### PR DESCRIPTION
**Pull request by dseif**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/591960b2bce2ac0/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/591960b2bce2ac0/output.txt

Total script time: 0.66 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/898bf9769388ac1/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/898bf9769388ac1/output.txt

Total script time: 1.04 mins

Server is running on http://pr383.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_cleanup** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/d6072e837b26cb3/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/d6072e837b26cb3/output.txt

Total script time: 0.60 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @cadecairos received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/aec375c7554aea3/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/aec375c7554aea3/output.txt

Total script time: 0.91 mins

Server is running on http://pr383.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @cadecairos received. Current queue size: 2

Live output at: http://botio.butyr.org:8000/4b8f0d5a0ae4ad5/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/4b8f0d5a0ae4ad5/output.txt

Total script time: 0.52 mins

Server is running on http://pr383.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/e65c3e55f3fbadb9baa29116c8e39f4a84600916

**Pull request closed without merging**
