### PR TITLE
[1879] [IE9] Blue gradients are an eyesore

### PR DESCRIPTION
**Pull request by stanica**
No more awful blue!

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @stanica received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/7b98a25ccc22e2c/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/7b98a25ccc22e2c/output.txt

Total script time: 0.47 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @stanica received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/0bc7d8a04d0b43e/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/0bc7d8a04d0b43e/output.txt

Total script time: 0.54 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @stanica received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/80fbb877fa4037e/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/80fbb877fa4037e/output.txt

Total script time: 2.00 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_cleanup** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/57c6b2d2af47549/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/57c6b2d2af47549/output.txt

Total script time: 0.24 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/47c3e77909d272a/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/47c3e77909d272a/output.txt

Total script time: 0.81 mins

Server is running on http://pr696.butyr.org/templates/basic/

**Comment by mjschranz** [comment]
Staged.

**Pull request closed without merging**
