### PR TITLE
T1786b

### PR DESCRIPTION
**Pull request by dseif**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @dseif received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/59e4b8549d2083a/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/59e4b8549d2083a/output.txt

Total script time: 0.23 mins

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/04987b223dc2334df45e1ea818508f3a6dcfe993

**Pull request closed without merging**
