### PR TITLE
[#1481] don't apply defaults on import.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @ScottDowne received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/b06b26b1cb95169/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/b06b26b1cb95169/output.txt

Total script time: 0.64 mins

Server is running on http://pr481.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Staged on storycamp: https://github.com/mozilla/butter/commit/398fead44fbc4fee6bab3624fb562baf29acaf60

**Pull request closed without merging**
