### PR TITLE
T1786

### PR DESCRIPTION
**Pull request by secretrobotron**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @dseif received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/e7c9e49746452c1/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/e7c9e49746452c1/output.txt

Total script time: 0.67 mins

Server is running on http://pr758.butyr.org/templates/basic/

**Comment by dseif** [comment]
YOU REWROTE IT

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/d80a6d397fab30c/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/d80a6d397fab30c/output.txt

Total script time: 1.23 mins

Server is running on http://pr758.butyr.org/templates/basic/

**Comment by jbuck** [comment]
@dseif Your reaction when you looked at this ticket: http://i.qkme.me/35g6bo.jpg

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @ScottDowne received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/6e09e28ffb064b5/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/6e09e28ffb064b5/output.txt

Total script time: 0.86 mins

Server is running on http://pr758.butyr.org/templates/basic/

**Comment by dseif** [comment]
@jbuck any Gandalf meme gets a +1 from me

**Comment by secretrobotron** [comment]
For the record, I didn't rewrite this. I just built on it very heavily. :D For serious, this code grew out of yours, like a man from childhood :P.

**Pull request closed without merging**
