### PR TITLE
Bug 2054 - Fix linting errors

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/b8bea54428b7687/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/b8bea54428b7687/output.txt

Total script time: 1.18 mins

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/173b529e6ebda2558f1fdd6c7b44f25e58d52430

**Pull request closed without merging**
