### PR TITLE
[1248] Move as much CSS as possible to LESS

### PR DESCRIPTION
**Pull request by stanica**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/8c030c33a46b20e/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/87cdd50004a72c0/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/8c030c33a46b20e/output.txt

Total script time: 0.49 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/87cdd50004a72c0/output.txt

Total script time: 0.66 mins

Server is running on http://pr607.butyr.org/templates/test.html

**Comment by jbuck** [comment]
wont-fixed in lighthouse

**Pull request closed without merging**
