### PR TITLE
Rebased1542

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @ScottDowne received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/fcf50dc0fd80271/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/fcf50dc0fd80271/output.txt

Total script time: 0.51 mins

Server is running on http://pr525.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Staged on storycamp: https://github.com/mozilla/butter/commit/cd4b21661350b0d95b803f6445a4adfaaa73eca6

**Pull request closed without merging**
