### PR TITLE
[#2056] Removed unneeded `&& true`

### PR DESCRIPTION
**Pull request by dseif**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @secretrobotron received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/431af4b50a2341c/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @secretrobotron received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/77116bc387d5697/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/431af4b50a2341c/output.txt

Total script time: 0.99 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/77116bc387d5697/output.txt

Total script time: 0.66 mins

Server is running on http://pr829.butyr.org/templates/basic/
Run the Test Suite: http://pr829.butyr.org/test/

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_cleanup** from @secretrobotron received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/507453f2980789e/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/507453f2980789e/output.txt

Total script time: 0.37 mins

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/8e00ff0c83456b165935dfedcc03b41868e4cfea

**Pull request closed without merging**
