### PR TITLE
[#1829] Define butter-editor-spacing in butter.ui.less

### PR DESCRIPTION
**Pull request by cadecairos**
https://webmademovies.lighthouseapp.com/projects/65733/tickets/1829

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @secretrobotron received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/93bfe81fbb645f1/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/93bfe81fbb645f1/output.txt

Total script time: 1.39 mins

Server is running on http://pr666.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_cleanup** from @secretrobotron received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/e1fefd0fd583fcd/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/e1fefd0fd583fcd/output.txt

Total script time: 1.06 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @dseif received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/f9e30aaa1430f38/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/f9e30aaa1430f38/output.txt

Total script time: 1.00 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @dseif received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/4ad0c1cd3886bd4/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/4ad0c1cd3886bd4/output.txt

Total script time: 0.60 mins

Server is running on http://pr666.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_cleanup** from @dseif received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/52a66c63971bb2b/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/52a66c63971bb2b/output.txt

Total script time: 0.96 mins

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/0785e0ba1f07e81c56019ce9d391e1fd2b22a4d9

**Pull request closed without merging**
