### PR TITLE
Do not pay attention to the man behind the bot

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_test** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/f7a33a55ff2f36e/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/f7a33a55ff2f36e/output.txt

Total script time: 0.26 mins

#### Hello world

Your Botio installation works! View full output for the list of files in this repo

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/432ee9a188beef2/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/432ee9a188beef2/output.txt

Total script time: 0.28 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/b91c512a85f3231/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/b91c512a85f3231/output.txt

Total script time: 0.73 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/09cb500ca0c7a43/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/09cb500ca0c7a43/output.txt

Total script time: 0.22 mins

Checking 36bf47c3032595016d609a0f39d8a9d3a115d028 of pull request #244

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/ef6644a4bf7a77b/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/ef6644a4bf7a77b/output.txt

Total script time: 0.41 mins

Checking 36bf47c3032595016d609a0f39d8a9d3a115d028 of pull request #244

#### Published

You can view your repo files at: http://butyr.org:8000/ef6644a4bf7a77b

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/a08ff453425829f/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/a08ff453425829f/output.txt

Total script time: 0.41 mins

Checking 36bf47c3032595016d609a0f39d8a9d3a115d028 of pull request #244

#### Published

You can view your repo files at: http://butyr.org:8000/a08ff453425829f

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/c813215b177f058/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/c813215b177f058/output.txt

Total script time: 0.70 mins

Checking 77a44c00b56180c60737aee9206a8ec8a37e3b8a of pull request #244

#### Published

You can view your repo files at: http://butyr.org:8000/c813215b177f058

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/0a8e9fa23052482/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/0a8e9fa23052482/output.txt

Total script time: 1.27 mins

#### Published

You can view your repo files at: http://butyr.org:8000/0a8e9fa23052482

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/7baf3ebbcc35e33/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/7baf3ebbcc35e33/output.txt

Total script time: 0.93 mins

#### Published

You can view your repo files at: http://butyr.org:8000/7baf3ebbcc35e33

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/ec7b4b72bcd066f/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/ec7b4b72bcd066f/output.txt

Total script time: 1.16 mins

#### Published

You can view your repo files at: http://butyr.org:8000/ec7b4b72bcd066f

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/a0f7c88db4b21d3/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 1

Live output at: http://butyr.org:8000/4d9fa7bed1773de/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/a0f7c88db4b21d3/output.txt

Total script time: 1.05 mins

#### Published

You can view your repo files at: http://butyr.org:8000/a0f7c88db4b21d3

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/4d9fa7bed1773de/output.txt

Total script time: 0.38 mins

#### Published

You can view your repo files at: http://butyr.org:8000/4d9fa7bed1773de

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/90e1868f1bdb8ad/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/90e1868f1bdb8ad/output.txt

Total script time: 2.00 mins

#### Published

You can view your repo files at: http://butyr.org:8000/90e1868f1bdb8ad

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/2114fdf7c521478/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/2114fdf7c521478/output.txt

Total script time: 0.83 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/e803f945344695f/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/e803f945344695f/output.txt

Total script time: 0.70 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/45e18dfb411eac3/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/45e18dfb411eac3/output.txt

Total script time: 0.76 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/5b4e93f54d0ecba/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/5b4e93f54d0ecba/output.txt

Total script time: 0.94 mins

We went too far

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/6191ca639d5fb63/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/6191ca639d5fb63/output.txt

Total script time: 0.79 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/7ddb60cbdea2858/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/7ddb60cbdea2858/output.txt

Total script time: 0.65 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/8168843ba0d145b/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/8168843ba0d145b/output.txt

Total script time: 2.00 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/bf3476c468186bd/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/bf3476c468186bd/output.txt

Total script time: 0.67 mins

Server failed to start

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/a53ba5b69585a20/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/a53ba5b69585a20/output.txt

Total script time: 0.43 mins

Server failed to start

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/56fa35d148d3d3d/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/56fa35d148d3d3d/output.txt

Total script time: 0.81 mins

Server failed to start

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/67d148a287669da/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/67d148a287669da/output.txt

Total script time: 0.15 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/929d4fd6ddb4ceb/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/929d4fd6ddb4ceb/output.txt

Total script time: 0.43 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/b1e96e534ee7c74/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/b1e96e534ee7c74/output.txt

Total script time: 0.69 mins

Server failed to start

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/be4753cb63c7656/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/be4753cb63c7656/output.txt

Total script time: 0.47 mins

Server failed to start

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/22d7587eea4c601/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/22d7587eea4c601/output.txt

Total script time: 1.13 mins

Server failed to start

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/37981785c99385b/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/37981785c99385b/output.txt

Total script time: 0.65 mins

Server is running on port:38932

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/2f442cd992dff07/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/2f442cd992dff07/output.txt

Total script time: 0.61 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/edb6e0eb5ed7a45/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/edb6e0eb5ed7a45/output.txt

Total script time: 0.41 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/d92d9ff0c6bb780/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/d92d9ff0c6bb780/output.txt

Total script time: 0.60 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/693801eab5ef640/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/693801eab5ef640/output.txt

Total script time: 0.40 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/b5e55a7b4694b70/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/b5e55a7b4694b70/output.txt

Total script time: 0.37 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/1740355df1cee36/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/1740355df1cee36/output.txt

Total script time: 0.45 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/e86fedd72a09d0f/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/e86fedd72a09d0f/output.txt

Total script time: 0.43 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/61b65093d87f36b/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/61b65093d87f36b/output.txt

Total script time: 0.33 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/51a9b65818b256e/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/51a9b65818b256e/output.txt

Total script time: 0.39 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/c50f7ab3184e1bc/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/c50f7ab3184e1bc/output.txt

Total script time: 0.65 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/70b0811b35ce301/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/70b0811b35ce301/output.txt

Total script time: 0.70 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/60dbd7b2a297c1c/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/60dbd7b2a297c1c/output.txt

Total script time: 0.48 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/73b472923cd8713/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/73b472923cd8713/output.txt

Total script time: 0.42 mins

Server is running on http://pr244.butyr.org

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/e3466e60d02ca69/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/e3466e60d02ca69/output.txt

Total script time: 0.60 mins

Server is running on http://pr244.butyr.org

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/5a386d6f9117742/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/5a386d6f9117742/output.txt

Total script time: 2.00 mins

Server is running on http://pr244.butyr.org

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/3c564deba4188f0/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/3c564deba4188f0/output.txt

Total script time: 2.00 mins

Server is running on http://pr244.butyr.org

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/369265e85db2489/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/369265e85db2489/output.txt

Total script time: 0.65 mins

Server is running on http://pr244.butyr.org

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/93d09ed9f5524d3/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/93d09ed9f5524d3/output.txt

Total script time: 0.79 mins

Server is running on http://pr244.butyr.org

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/c75ca80c32b27e6/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/c75ca80c32b27e6/output.txt

Total script time: 0.39 mins

Server is running on http://pr244.butyr.org

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/bb41a827e69592d/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/bb41a827e69592d/output.txt

Total script time: 0.55 mins

Server is running on http://pr244.butyr.org

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/01de40c9dd092b2/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/01de40c9dd092b2/output.txt

Total script time: 0.61 mins

Server is running on http://pr244.butyr.org

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/4cb1ce057708327/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://butyr.org:8000/4cb1ce057708327/output.txt

Total script time: 0.51 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/79779c8813fb376/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/79779c8813fb376/output.txt

Total script time: 1.33 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/d4ce96679e11364/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/d4ce96679e11364/output.txt

Total script time: 0.75 mins

**Comment by jbuck** [comment]
asdf

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://butyr.org:8000/8c006dd0c0df64a/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 1

Live output at: http://butyr.org:8000/92ff899f18a8a57/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 2

Live output at: http://butyr.org:8000/cb3d372b5130b0e/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 3

Live output at: http://butyr.org:8000/53a0144c71dc5dc/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 4

Live output at: http://butyr.org:8000/f4ebfdb830383d7/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Help

Available commands:

```
preview
check
```

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/8c006dd0c0df64a/output.txt

Total script time: 0.57 mins

Server failed to start

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/92ff899f18a8a57/output.txt

Total script time: 0.47 mins

Server failed to start

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/cb3d372b5130b0e/output.txt

Total script time: 0.40 mins

Server failed to start

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/53a0144c71dc5dc/output.txt

Total script time: 0.49 mins

Server failed to start

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://butyr.org:8000/f4ebfdb830383d7/output.txt

Total script time: 0.55 mins

Server failed to start

**Pull request closed without merging**
