### PR TITLE
M t1135

### PR DESCRIPTION
**Pull request by k88hudson**
Testing for templates - editor hides manifest options marked 'hidden'

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/a01f7d4b20f9f09/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/a01f7d4b20f9f09/output.txt

Total script time: 0.45 mins

Server is running on http://pr368.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Closing because we have already landed the image2 plugin, so I think this can just be closed. @k88hudson just re-open this if I've closed it incorrectly.

**Pull request closed without merging**
