### PR TITLE
T1694

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @dseif received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/31943e5e4428ea8/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/31943e5e4428ea8/output.txt

Total script time: 0.52 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @dseif received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/84279f22c9a866e/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/84279f22c9a866e/output.txt

Total script time: 0.65 mins

Server is running on http://pr608.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/510b88cd80393b024fc3777abd2539eccb0bfe0b

**Pull request closed without merging**
