### PR TITLE
Bug 2048 - Change embed div ids to match template ids

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @cadecairos received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/30fa86582a5bb22/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/30fa86582a5bb22/output.txt

Total script time: 0.82 mins

Server is running on http://pr830.butyr.org/templates/basic/
Run the Test Suite: http://pr830.butyr.org/test/

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @ScottDowne received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/2b7d10603fd2331/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/2b7d10603fd2331/output.txt

Total script time: 1.44 mins

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/7705615152822d770c3c6b5b06dfe5bf42968665

**Pull request closed without merging**
