### PR TITLE
[#2034] Remove photo plugin from basic template

### PR DESCRIPTION
**Pull request by cadecairos**
https://webmademovies.lighthouseapp.com/projects/65733-popcorn-maker/tickets/2034-remove-photo-plugin-from-basic

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @humphd received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/aa67e0bef2ceba5/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @humphd received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/3a1d4fc2fd3ac30/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/aa67e0bef2ceba5/output.txt

Total script time: 1.27 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/3a1d4fc2fd3ac30/output.txt

Total script time: 0.77 mins

Server is running on http://pr813.butyr.org/templates/basic/
Run the Test Suite: http://pr813.butyr.org/test/

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/188ad8fce3a90c24f1959ef0875ebf2249ffef90

**Pull request closed without merging**
