### PR TITLE
[1887] [IE9] Replaced drop.png with one that works in IE9

### PR DESCRIPTION
**Pull request by stanica**
The old logo may have been corrupt or in a format not supported by IE9. This one works in all browsers.

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @stanica received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/e4e1b73705ca60b/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/e4e1b73705ca60b/output.txt

Total script time: 0.45 mins

**Comment by jbuck** [comment]
wont-fixed in Lighthouse

**Pull request closed without merging**
