### PR TITLE
Improve performance of config merges

### PR DESCRIPTION
**Pull request by humphd**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/9666fa0da34b055/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/b7c93f6aef4127e/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/9666fa0da34b055/output.txt

Total script time: 0.36 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/b7c93f6aef4127e/output.txt

Total script time: 0.58 mins

Server is running on http://pr362.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Closing in favour of pull request #644

**Pull request closed without merging**
