### PR TITLE
Update Popcorn [#1405]

### PR DESCRIPTION
**Pull request by jbuck**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @jbuck received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/0407c718d48f427/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/0407c718d48f427/output.txt

Total script time: 0.54 mins

Server is running on http://pr424.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @jbuck received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/42736a5712e93b5/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/42736a5712e93b5/output.txt

Total script time: 0.34 mins

**Comment by mjschranz** [comment]
Jon was taking too long.

New pull request is here https://github.com/mozilla/butter/pull/431

**Pull request closed without merging**
