### PR TITLE
Instrumenting src/ui/header.js for debugging

### PR DESCRIPTION
**Pull request by humphd**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @humphd received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/6d18bff46b32f1a/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/6d18bff46b32f1a/output.txt

Total script time: 0.94 mins

Server is running on http://pr384.butyr.org/templates/test.html

**Comment by jbuck** [comment]
Resolved by pull request #401 and #402

**Pull request closed without merging**
