### PR TITLE
Robots for demo

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/ac756fbdc66632d/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/ac756fbdc66632d/output.txt

Total script time: 0.67 mins

Server is running on http://pr447.butyr.org/templates/test.html

**Comment by jbuck** [comment]
old ticket

**Pull request closed without merging**
