### PR TITLE
[t2334] Don't destroy trackevent when adding/removing them from tracks.

### PR DESCRIPTION
**Pull request by secretrobotron**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/a2d30450132a801/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @mjschranz received. Current queue size: 1

Live output at: http://botio.butyr.org:8000/b8b0031ebe8b935/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/a2d30450132a801/output.txt

Total script time: 1.32 mins

Server is running on http://pr1087.butyr.org/templates/basic/
Run the Test Suite: http://pr1087.butyr.org/test/

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/b8b0031ebe8b935/output.txt

Total script time: 2.79 mins

**Comment by mjschranz** [comment]
#1085 is taking in these changes.

**Pull request closed without merging**
