### PR TITLE
M newscaster

### PR DESCRIPTION
**Pull request by k88hudson**
Testing newscaster template

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/92318b66c426cf0/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/92318b66c426cf0/output.txt

Total script time: 0.42 mins

Server is running on http://pr370.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/c1e729af3aea009/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/c1e729af3aea009/output.txt

Total script time: 0.68 mins

Server is running on http://pr370.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/b9e3b6ed8f8bc61/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/b9e3b6ed8f8bc61/output.txt

Total script time: 0.66 mins

Server is running on http://pr370.butyr.org/templates/test.html

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @k88hudson received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/6c8adc69a47cb24/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/6c8adc69a47cb24/output.txt

Total script time: 0.97 mins

Server is running on http://pr370.butyr.org/templates/test.html

**Comment by jbuck** [comment]
I will close this because it feels right.

**Pull request closed without merging**
