### PR TITLE
[#1765] changed flaot right to float left to get proper alignment.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_check** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/d2e9c9da5d28850/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/d2e9c9da5d28850/output.txt

Total script time: 0.66 mins

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @mjschranz received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/fcec07facbbb4b3/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Failed

Full output at http://botio.butyr.org:8000/fcec07facbbb4b3/output.txt

Total script time: 2.00 mins

**Comment by jbuck** [comment]
Staged on master: https://github.com/mozilla/butter/commit/9c46c5c0c38338cf6ba99df4a16dbd931f1c553b

**Pull request closed without merging**
