### PR TITLE
[1926] Use custom controls in embed iframe

### PR DESCRIPTION
**Pull request by humphd**

### CODE REVIEW

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Received

Command **cmd_preview** from @ScottDowne received. Current queue size: 0

Live output at: http://botio.butyr.org:8000/d71257a0c6d3a65/output.txt

**Comment by ghost** [comment]
#### From: Bot.io (butyr.org)

---

# Success

Full output at http://botio.butyr.org:8000/d71257a0c6d3a65/output.txt

Total script time: 1.16 mins

Server is running on http://pr731.butyr.org/templates/basic/

**Comment by jbuck** [comment]
Rebased on master: https://github.com/mozilla/butter/commit/0f1d7dbb5b7ea44e295f7f8d2a96b8a9d56a5a50

**Pull request closed without merging**
